-- 0004_orders.sql
-- Orders, their line items, and recurring schedules.

-- ────────────────────────────────────────────────────────────────────────
-- recurring_orders — created before `orders`, which references it.
-- ────────────────────────────────────────────────────────────────────────
create table public.recurring_orders (
  id          uuid primary key default gen_random_uuid(),
  customer_id uuid not null references public.customers(id) on delete cascade,
  frequency   text not null check (frequency in ('weekly','fortnightly','monthly')),
  -- 0 = SUNDAY, matching Postgres extract(dow from date) AND date-fns
  -- getDay(). ISO numbering (1 = Monday) is NOT used anywhere in this app.
  day_of_week  int check (day_of_week between 0 and 6),
  -- Capped at 28, which removes "the 31st of February" entirely.
  day_of_month int check (day_of_month between 1 and 28),
  starts_on   date not null,
  ends_on     date,
  active      boolean not null default true,
  notes       text,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now(),

  constraint recurring_orders_day_matches_frequency check (
       (frequency in ('weekly','fortnightly') and day_of_week  is not null)
    or (frequency = 'monthly'                 and day_of_month is not null)
  ),
  constraint recurring_orders_ends_after_starts check (
    ends_on is null or ends_on >= starts_on
  )
);
-- There is deliberately NO paused_until column. Pausing for a holiday is
-- toggling `active`.

create index idx_recurring_orders_customer on public.recurring_orders (customer_id);
create index idx_recurring_orders_active   on public.recurring_orders (active) where active;

create trigger trg_recurring_orders_updated_at
  before update on public.recurring_orders
  for each row execute function public.f_set_updated_at();

create table public.recurring_order_items (
  id                 uuid primary key default gen_random_uuid(),
  recurring_order_id uuid not null references public.recurring_orders(id) on delete cascade,
  product_id         uuid not null references public.products(id) on delete restrict,
  quantity           int  not null check (quantity > 0),
  created_at         timestamptz not null default now(),
  unique (recurring_order_id, product_id)
);

create index idx_recurring_order_items_parent  on public.recurring_order_items (recurring_order_id);
create index idx_recurring_order_items_product on public.recurring_order_items (product_id);

-- ────────────────────────────────────────────────────────────────────────
-- orders
-- ────────────────────────────────────────────────────────────────────────
create table public.orders (
  id           uuid primary key default gen_random_uuid(),
  customer_id  uuid not null references public.customers(id) on delete restrict,
  order_number int  not null unique generated by default as identity,
  status       text not null default 'confirmed'
                    check (status in ('draft','confirmed','in_production','delivered','cancelled')),
  ordered_on    date not null default public.f_today(),
  delivery_date date not null,
  recurring_order_id uuid references public.recurring_orders(id) on delete set null,

  -- Snapshotted at creation so a customer moving does not rewrite
  -- historical delivery sheets.
  delivery_address        text,
  delivery_notes_snapshot text,

  notes      text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  -- Redundant against the primary key, but Postgres requires a unique
  -- constraint on the exact columns a composite FK references. This is
  -- what lets invoice_orders (Phase 5) make it structurally impossible to
  -- put cafe A's order on cafe B's invoice.
  unique (id, customer_id)
);

create index idx_orders_delivery_date     on public.orders (delivery_date);
create index idx_orders_customer_delivery on public.orders (customer_id, delivery_date desc);
create index idx_orders_status            on public.orders (status);
create index idx_orders_recurring         on public.orders (recurring_order_id)
  where recurring_order_id is not null;

-- Duplicate-generation guard.
--
-- NOTE this index is PARTIAL. Any ON CONFLICT that wants to use it as an
-- arbiter MUST repeat the predicate:
--     on conflict (recurring_order_id, delivery_date)
--       where recurring_order_id is not null do nothing
-- Omitting the `where` raises 42P10. See 0005b.
create unique index idx_orders_recurring_delivery
  on public.orders (recurring_order_id, delivery_date)
  where recurring_order_id is not null;

create trigger trg_orders_updated_at
  before update on public.orders
  for each row execute function public.f_set_updated_at();

-- ────────────────────────────────────────────────────────────────────────
-- order_items — prices AND names are snapshots.
-- Renaming or repricing a product must never alter a past order or make a
-- historical invoice reprint differently.
-- ────────────────────────────────────────────────────────────────────────
create table public.order_items (
  id           uuid primary key default gen_random_uuid(),
  order_id     uuid not null references public.orders(id)   on delete cascade,
  product_id   uuid not null references public.products(id) on delete restrict,
  product_name text not null,                                       -- snapshot
  quantity     int  not null check (quantity > 0),
  unit_price   numeric(12,3) not null check (unit_price >= 0),       -- snapshot
  unit_cost    numeric(12,3) not null default 0 check (unit_cost >= 0), -- snapshot
  line_total   numeric(12,3) generated always as (quantity * unit_price) stored,
  created_at   timestamptz not null default now(),
  unique (order_id, product_id)
);

create index idx_order_items_order   on public.order_items (order_id);
create index idx_order_items_product on public.order_items (product_id);

-- ────────────────────────────────────────────────────────────────────────
-- v_order_totals
--
-- Status filtering is NOT applied here — this view reports on every order
-- including drafts and cancellations. Callers filter explicitly. Revenue
-- and margin must count only ('confirmed','in_production','delivered').
-- ────────────────────────────────────────────────────────────────────────
create view public.v_order_totals
with (security_invoker = on) as
select
  o.id            as order_id,
  o.customer_id,
  o.order_number,
  o.status,
  o.ordered_on,
  o.delivery_date,
  o.recurring_order_id,
  coalesce(sum(oi.line_total), 0)::numeric(12,3)               as subtotal,
  coalesce(sum(oi.quantity * oi.unit_cost), 0)::numeric(12,3)  as total_cost,
  (coalesce(sum(oi.line_total), 0)
   - coalesce(sum(oi.quantity * oi.unit_cost), 0))::numeric(12,3) as gross_margin,
  coalesce(sum(oi.quantity), 0)::int                           as total_units,
  count(oi.id)::int                                            as line_count
from public.orders o
left join public.order_items oi on oi.order_id = o.id
group by o.id;

revoke all on public.v_order_totals from anon;

create view public.v_order_list
with (security_invoker = on) as
select
  t.*,
  c.name                             as customer_name,
  o.notes                            as notes,
  (o.recurring_order_id is not null) as is_recurring
from public.v_order_totals t
join public.orders    o on o.id = t.order_id
join public.customers c on c.id = t.customer_id;

revoke all on public.v_order_list from anon;

-- ────────────────────────────────────────────────────────────────────────
-- RLS
-- ────────────────────────────────────────────────────────────────────────
alter table public.orders                enable row level security;
alter table public.order_items           enable row level security;
alter table public.recurring_orders      enable row level security;
alter table public.recurring_order_items enable row level security;

create policy "app users have full access" on public.orders
  for all to authenticated
  using      ((select exists (select 1 from public.profiles where id = (select auth.uid()))))
  with check ((select exists (select 1 from public.profiles where id = (select auth.uid()))));

create policy "app users have full access" on public.order_items
  for all to authenticated
  using      ((select exists (select 1 from public.profiles where id = (select auth.uid()))))
  with check ((select exists (select 1 from public.profiles where id = (select auth.uid()))));

create policy "app users have full access" on public.recurring_orders
  for all to authenticated
  using      ((select exists (select 1 from public.profiles where id = (select auth.uid()))))
  with check ((select exists (select 1 from public.profiles where id = (select auth.uid()))));

create policy "app users have full access" on public.recurring_order_items
  for all to authenticated
  using      ((select exists (select 1 from public.profiles where id = (select auth.uid()))))
  with check ((select exists (select 1 from public.profiles where id = (select auth.uid()))));
